# Generated by Django 4.1.7 on 2023-04-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
                ('fecha', models.DateField(auto_now_add=True, unique=True)),
                ('porcentaje', models.FloatField()),
                ('consecutivo', models.IntegerField()),
            ],
        ),
    ]
