# Generated by Django 4.1.7 on 2023-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleta',
            name='telefono',
            field=models.CharField(default=3135500, max_length=100),
            preserve_default=False,
        ),
    ]
