# Generated by Django 4.1.7 on 2023-04-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0003_alter_ruleta_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleta',
            name='cedula',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ruleta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='ruleta',
            unique_together={('cedula', 'fecha')},
        ),
    ]
