# Generated by Django 4.1.7 on 2023-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteo', '0004_alter_ruleta_cedula_alter_ruleta_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleta',
            name='terminos',
            field=models.BooleanField(default=True),
        ),
    ]
